# Generated by Django 3.2.14 on 2022-08-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220804_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedorganizationtocustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.customerprofile'),
        ),
        migrations.AlterField(
            model_name='associatedorganizationtocustomer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='users.organization'),
        ),
    ]
